# file generated by poetry-dynamic-versioning
from typing import TYPE_CHECKING

__version__: str = "0.0.0"  # This will be replaced during build
__version_tuple__: tuple[int, ...] = (0, 0, 0)  # This will be replaced during build
__commit_id__: str | None = None  # This will be replaced during build

# For compatibility with setuptools-scm test expectations
VERSION_TUPLE = __version_tuple__
COMMIT_ID = __commit_id__

if TYPE_CHECKING:
    # Version will be injected by poetry-dynamic-versioning
    pass